load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "glm",
    hdrs = glob([
        "glm/glm/*.hpp",
        "glm/glm/ext/*.hpp",
        "glm/glm/gtc/*.hpp",
        "glm/glm/gtx/*.hpp",
        "glm/glm/simd/*.h",
    ]),
    srcs = glob([
        "glm/glm/detail/*.hpp",
        "glm/glm/**/*.inl",
    ]),
    includes = ["glm"],
    visibility = ["//visibility:public"],
)

